apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp-chart.fullname" . }}
  labels:
    app: {{ include "myapp-chart.name" . }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.java.port }}
      targetPort: {{ .Values.java.port }}
      protocol: TCP
      name: java
    - port: {{ .Values.angular.port }}
      targetPort: {{ .Values.angular.port }}
      protocol: TCP
      name: angular
  selector:
    app: {{ include "myapp-chart.name" . }}
